# Exercise on Functions

## Task1:

In [3]:
def convert_length(value, from_unit):
  if(from_unit == "m"):
    return value * 3.28084
  elif(from_unit == "ft"):
    return value / 3.28084
  else:
    return "Invalid Unit"

def convert_weight(value, from_unit):
  if(from_unit == "kg"):
    return value * 2.20462
  elif(from_unit == "lb"):
    return value / 2.20462
  else:
    return "Invalid Unit"

def convert_volume(value, from_unit):
  if(from_unit == "L"):
    return value * 0.264172
  elif(from_unit == "gal"):
    return value / 0.264172
  else:
    return "Invalid Unit"


def main():
  print("Unit conversion")

  try:
    conversion_type = int(input("Choose 1 for length, 2 for weight, 3 for volume: "))
    value = float(input("Enter the value: "))

    if(conversion_type == 1):
      from_unit = input("Enter the unit to convert from (m/ft): ")
      print(convert_length(value, from_unit))

    elif(conversion_type == 2):
      from_unit = input("Enter the unit to convert from (kg/lb): ")
      print(convert_weight(value, from_unit))

    elif(conversion_type == 3):
      from_unit = input("Enter the unit to convert from (L/gal): ")
      print(convert_volume(value, from_unit))

    else:
      print("Invalid choice")


  except ValueError as e:
    print(f"Error: {e}. Please enter a valid number and unit")

main()



Unit conversion
Choose 1 for length, 2 for weight, 3 for volume: 1
Enter the value: 2
Enter the unit to convert from (m/ft): ft
0.6095999804928006


## Task2:

In [4]:
def sum_of_numbers(numbers):
  """
    Calculate the sum of a list of numbers.
    :param numbers: List of numeric values.
    :return: Sum of the numbers.
  """
  sum = 0
  for num in numbers:
    sum += num
  return sum

def average_of_numbers(numbers):
  """
  Calculate the average of a list of numbers.
  :param numbers: List of numeric values.
  :return: Average of the numbers, or 0 if the list is empty.
  """
  if len(numbers) == 0:
    return 0
  return sum_of_numbers(numbers) / len(numbers)

def maximum_number(numbers):
  """
  Find the maximum number in a list.
  :param numbers: List of numeric values.
  :return: Maximum value, or 0 if the list is empty.
  """
  if len(numbers) == 0:
    return 0
  max = numbers[0]
  for num in numbers:
    if(num > max):
      max = num
  return max

def minimum_number(numbers):
  """
  Find the minimum number in a list.
  :param numbers: List of numeric values.
  :return: minimum value, or 0 if the list is empty.
  """
  if len(numbers) == 0:
    return 0
  min = numbers[0]
  for num in numbers:
    if(num < min):
      min = num
  return min

def main():
  """
  Main function to take user input and perform selected operation.
  """
  try:
    number = [float(x) for x in input("Enter the numbers separated by space: ").split()]
    operation_type = int(input("Choose 1 for sum, 2 for average, 3 for maximum, 4 for minimum: "))

    if(operation_type == 1):
      print(f"Sum of the numbers: {sum_of_numbers(number)}")
    elif(operation_type == 2):
      print(f"Average of the numbers: {average_of_numbers(number)}")
    elif(operation_type == 3):
      print(f"Maximum of the numbers: {maximum_number(number)}")
    elif(operation_type == 4):
      print(f"Minimum of the numbers: {minimum_number(number)}")

    else:
      print("Invalid choice")

  except ValueError as e:
    print(f"Error: {e}. Please enter a valid number")

main()

Enter the numbers separated by space: 1 3 5
Choose 1 for sum, 2 for average, 3 for maximum, 4 for minimum: 1
Sum of the numbers: 9.0


# Exercise on List Manipulation:

## Extract Every Other Element:

In [5]:
def extract_every_other(lst):
  #  return lst[::2] # list[start:stop:step]

  if not isinstance(lst, list):
      raise TypeError("Input must be a list.")
  result = []
  for i in range(0,len(lst),2):
    result.append(lst[i])
  return result


try:
    new_lst = extract_every_other([1, 2, 3, 4, 5, 6])
    print(new_lst)
except (TypeError, ValueError) as e:
    print(f"Error: {e}")

[1, 3, 5]


## Slice a Sublist:

In [6]:
def get_sublist(lst, start, end):
  return lst[start:end]

new_lst = get_sublist([1, 2, 3, 4, 5, 6],2, 4)
new_lst

[3, 4]

In [7]:
def reverse_list(lst):
  return lst[::-1]
reverse_list([1, 2, 3, 4, 5])

[5, 4, 3, 2, 1]

### Remove the First and Last Elements:

In [11]:
def remove_first_last(lst):
  return lst[1:-1:]

remove_first_last([1, 2, 3, 4, 5])

[2, 3, 4]

### Get the First n Elements:

In [14]:
def get_first_n(lst, n):
  return lst[:n]
n = int(input("Enter n number to return first n element"))
get_first_n([1, 2, 3, 4, 5],n)

Enter n number to return first n element3


[1, 2, 3]

### Extract Elements from the End:

In [15]:
def get_lst_n(lst, n):
  return lst[-n:]
n = int(input("Enter number to return n last element"))

get_lst_n([1, 2, 3, 4, 5],n)

Enter number to return n last element4


[2, 3, 4, 5]

### Extract Elements in Reverse Order

In [16]:
def reverse_skip(lst):
  return lst[-2::-2]

reverse_skip([1, 2, 3, 4, 5, 6])

[5, 3, 1]

## Exercise on Nested List:

### Flatten a Nested List:

In [17]:
def flatten(lst):

  flat_list = []

  for sublist in lst:
    if isinstance(sublist, list):
      flat_list.extend(sublist)
    else:
      flat_list.append(sublist)
  return flat_list

nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))

[1, 2, 3, 4, 5]


In [18]:
def access_nested_element(lst, indices):
  return lst[indices[0]][indices[1]]

access_nested_element( [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1,2])

6

In [19]:
def sum_nested(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
        total += sum_nested(item)
    else:
        total += item
  return total


nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))


21


In [20]:
def remove_element(lst, elm):
  for i, sublist in enumerate(lst):
    for j, num in enumerate(sublist):
      if num == 2:
        lst[i].pop(j)

  return lst

remove_element([[1, 2], [3, 2], [4, 5]], 2)

[[1], [3], [4, 5]]

In [21]:
def find_max(lst):
    max_value = float('-inf')  # Initialize with negative infinity

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max
        else:
            max_value = max(max_value, item)  # Compare numbers

    return max_value


nested_list = [[1, 2], [3, [4, 5]], 6]
find_max(nested_list)


6

In [22]:
def count_cccurrences(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item,list):
      for num in item:
        if elem == num:
          count +=1
    else:
      if elem == item:
        count +=1

  return count

lst =  [[1, 2], [2, 3], [2, 4]]
count_cccurrences(lst,2)

3

In [23]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):  # If item is a list, recursively flatten it
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)  # Append non-list elements directly
    return flat_list


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
deep_flatten(nested_list)


[1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):  # If item is a list, recursively flatten it
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)  # Append non-list elements directly
    return flat_list


nested_list =[[1, 2], [3, 4], [5, 6]]
new_list = deep_flatten(nested_list)

sum(new_list)/len(new_list)


3.5

# NumPy

## Basic Vector and Matrix Operation with Numpy

### Problem - 1: Array Creation:

In [25]:
import numpy as np

**Initialize an empty array with size 2X2**

In [26]:
empty_array = np.empty((2,2))
empty_array

array([[2.35904039e-316, 0.00000000e+000],
       [9.38185117e-154, 1.16304933e+214]])

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Initialize an all-one array with size 4X2**

In [28]:
one_array = np.ones((4,2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**Return a new array of given shape and type, filled with fill value**

In [29]:
fill_value_array = np.full((3,2), 7) #create 3X2 size of matrix with value 7 on each
fill_value_array

array([[7, 7],
       [7, 7],
       [7, 7]])

Return a new array of zeros with same shape and type as a given array

In [30]:
sample_array = np.array([[4, 5], [6, 7]])
print(sample_array)
print("\nZero Array:")
zero_array = np.zeros_like(sample_array)
print(zero_array)

[[4 5]
 [6 7]]

Zero Array:
[[0 0]
 [0 0]]


**Return a new array of ones with same shape and type as a given array**

In [31]:
ones_like_array = np.ones_like(sample_array)
ones_like_array

array([[1, 1],
       [1, 1]])

**Convert an existing list to a NumPy array**

In [32]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
numpy_array

array([1, 2, 3, 4])

### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

**Create an array with values ranging from 10 to 49**

In [33]:
array_10_49 = np.arange(10, 50)
array_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Create a 3X3 matrix with values ranging from 0 to 8.

In [34]:
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}
**bold text**

In [35]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function} **bold text**

In [36]:
random_array = np.random.random(30)
random_array.mean()

0.5202304551586321

**Create a 10X10 array with random values and find the minimum and maximum values.**

In [37]:
random_matrix  = np.random.random((10,10))
# print(random_matrix)
print(f"Minimum value: {random_matrix.min()}")
print(f"Maximum value: {random_matrix.max()}")

Minimum value: 0.014715228760905696
Maximum value: 0.9929603438848447


**Create a zero array of size 10 and replace 5th element with 1.**

In [38]:
zero_array  = np.zeros(10)
zero_array[4] = 1
zero_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Reverse an array arr = [1,2,0,0,4,0].**

In [39]:
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
reversed_arr

array([0, 4, 0, 0, 2, 1])

**Create a 2d array with 1 on border and 0 inside.**

In [40]:
boarder_array = np.ones((5,5))
boarder_array[1:-1, 1:-1] = 0
boarder_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [41]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Problem - 3: Array Operations:


In [42]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [43]:
x+y

array([[ 6,  8],
       [10, 13]])

In [44]:
x-y

array([[-4, -4],
       [-4, -3]])

In [45]:
x*3

array([[ 3,  6],
       [ 9, 15]])

In [46]:
np.square(x)

array([[ 1,  4],
       [ 9, 25]])

In [47]:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("\nDot product of v and w:", dot_vw)
print("\nDot product of x and v:\n", dot_xv)
print("\nDot product of x and y:\n", dot_xy)


Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]


In [48]:
print(x)
print("\n")
print(y)

[[1 2]
 [3 5]]


[[5 6]
 [7 8]]


In [49]:
# 6. Concatenate x and y along rows
concat_xy = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy)

# Concatenate v and w along columns
concat_vw = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw)



Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]


In [50]:
# 7. Concatenating x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)


Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### Problem - 4: Matrix Operations:

1. Prove
𝐴
⋅
𝐴
−
1
=
𝐼
A⋅A
−1
 =I

In [52]:
A = np.array([[3, 4], [7, 8]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by its inverse
I = np.dot(A, A_inv)

# Print results
print("A * A^-1:\n", I)

# Check if it's an identity matrix
print("\nIs A * A^-1 approximately equal to I? ", np.allclose(I, np.eye(2)))


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^-1 approximately equal to I?  True


**To prove matrix multiplication is not commutative, we compute:**

𝐴
𝐵
AB (A multiplied by B)
𝐵
𝐴
BA (B multiplied by A)
Check if
𝐴
𝐵
=
𝐵
𝐴
AB=BA


In [53]:
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print results
print("\nAB:\n", AB)
print("\nBA:\n", BA)

# Check if they are equal
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))



AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?  False


Prove
(
𝐴
𝐵
)
𝑇
=
𝐵
𝑇
𝐴
𝑇
(AB)
T
 =B
T
 A
T

The transpose of a product of two matrices follows the rule:

(
𝐴
𝐵
)
𝑇
=
𝐵
𝑇
𝐴
𝑇
(AB)
T
 =B
T
 A
T

In [54]:
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T and A^T
B_T = np.transpose(B)
A_T = np.transpose(A)

# Compute B^T A^T
BT_AT = np.dot(B_T, A_T)

# Print results
print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", BT_AT)

# Check if they are equal
print("\nIs (AB)^T equal to B^T A^T? ", np.array_equal(AB_T, BT_AT))



(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T?  True


Solving the Linear System Using the Inverse Method


In [55]:
# Define matrix A (coefficients)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

# Define matrix B (constants)
B = np.array([-1, -3, 9])

# Solve for X using inverse
A_inv = np.linalg.inv(A)  # Compute inverse of A
X = np.dot(A_inv, B)  # Compute X

# Print results
print("\nSolution for x, y, z:\n", X)



Solution for x, y, z:
 [ 2.  1. -2.]


Solving Using np.linalg.solve

In [56]:
# Solve directly using np.linalg.solve
X_solve = np.linalg.solve(A, B)

# Print results
print("\nSolution using np.linalg.solve:\n", X_solve)



Solution using np.linalg.solve:
 [ 2.  1. -2.]
